name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install
        run: npm i
      - name: Test app
        run: npm run test
      - name: List app
        run: npm run lint
      - name: Build app
        run: npm run build
      - name: Deploy
        run: echo Deploy...